#!bin/csh
# cshell script to generate a .html file summarising the  results of a dissection analysis 
# of a IceCube neutrino track event 
# usage: source newtrack trackname MJD GCN_Number
# example source newtrack 190724A 59000.22 
if ($#argv < 3 ) then
 echo  "missing parameters"
 echo  "USAGE: source newtrack trackname MJD GCN_number "
 echo  "example source newtrack 190724A 59000.22 24981"
 exit
endif
mkdir IC$1 
cp -r IceCubeTemplate_Candidates_files IC$1/IceCube$1_files
cp IceCubeTemplate_1Candidate.html IC$1/index.html
vim -c "1,%s/IceCube yyyy/IceCube $1/g" -c 1,%s/ICyyyy/IC$1/g -c "1,%s/MJD aaaa/MJD $2/" -c 1,%s/gggg/$3/g -c 1,%s/tttt/$1/g -c 1,%s/rrrr/$1/g -c x IC$1/index.html 
